theme: jekyll-theme-minimal
title: Title
description: Howdy all, this is a fun project for me to learn how to utilize GitHub + Git! My background: MSCE Student with a BS in Applied Math and a concentration in Computer Science
